---
title: "CaseStudy2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(caret)
library(leaps)
library(MASS)
```

```{r import, message=FALSE}
dataset <- read_csv("CaseStudy2-data.csv",
                    col_types = cols(EmployeeCount = col_skip(), ID = col_skip(), Over18 = col_skip(), Rand = col_skip(), StandardHours = col_skip()))
```

```{r set to binary}
dataset$Attrition[dataset$Attrition=="Yes"] <- 1
dataset$Attrition[dataset$Attrition=="No"] <- 0
```

```{r AIC model}
model_aic <- lm(Attrition ~ ., data = dataset)
step.model_both <- stepAIC(model_aic, direction = "both", trace = FALSE)
step.model_forward <- stepAIC(model_aic, direction = "forward", trace = FALSE)
step.model_backward <- stepAIC(model_aic, direction = "backward", trace = FALSE)
aic_both <- summary(step.model_both)
aic_forward <- summary(step.model_forward)
aic_backward <- summary(step.model_backward)
aic_both$adj.r.squared
aic_forward$adj.r.squared
aic_backward$adj.r.squared
```

```{r ugh}
dataset$Attrition <- as.factor(dataset$Attrition)
set.seed(1)
train.control <- trainControl(method = "cv", number = 3)
step.model <- caret::train(Attrition ~ ., data = dataset, method = "glmStepAIC", trControl = train.control)

train.control1 <- trainControl(method = "LOOCV", number = 3)
step.model1 <- caret::train(Attrition ~ ., data = dataset, method = "glmStepAIC", trControl = train.control1)

train.control2 <- trainControl(method = "none", number = 3)
step.model2 <- caret::train(Attrition ~ ., data = dataset, method = "glmStepAIC", trControl = train.control2)

#step.model$results
#step.model1$results
#step.model2$results
#method cv, LOOCV, none
```


